### PR TITLE
Enable IMAP ID extension

### PR DESCRIPTION
**Pull request by foxcpp**

### CODE REVIEW

**Comment by emersion** [comment]
TBH I'd rather not support this extension…

**Comment by foxcpp** [comment]
>TBH I'd rather not support this extension…

Why?

**Comment by emersion** [comment]
This encourages clients to have per-server quirks. And if by chance clients don't do that, this doesn't have any value.

Do you have a use-case in mind?

**Comment by foxcpp** [comment]
Internet-wide scans for collecting statistics of used server software?

**Comment by emersion** [comment]
Meh, I don't care how many people use maddy.

**Comment by foxcpp** [comment]
Alright then. No ID.

**Pull request closed without merging**
